apiVersion: apps/v1
kind: Deployment
metadata:
  name: charityreports
spec:
  selector:
    matchLabels:
      run: charityreports
  replicas: 1
  template:
    metadata:
      labels:
        run: charityreports
    spec:
      containers:
        - name: charityreports
          image: fjmendes1994/charityreports:0.0.3
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: charityreports
  labels:
    run: charityreports
spec:
  selector:
    run: charityreports
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30420

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default